image: alpine/edge
sources:
  - git@git.sr.ht:~slondr/diarchy
packages:
  - elixir
tasks:
  - build: |
      cd diarchy
      mix local.hex --force
      mix local.rebar --force
      mix setup
      mix compile --warnings-as-errors
  - test: |
      cd diarchy
      mix local.hex --force
      mix local.rebar --force
      mix setup
      mix test
triggers:
  - action: email
    condition: failure
    to: Eric S. Londres <ericlondres@outlook.com>

      
